namespace inConcert.iMS.Enums
{
   public enum ResultStatus
   {
      SUCCESS,
      ERROR,
      NOT_FOUND,
      NOT_AUTHORIZED,
      ACCESS_DENIED,
      BAD_REQUEST,
      NOT_NULL,
      CONFLICT,
      COMMERCIAL_ROW_DUPLICATE,
      COMMERCIAL_ROW_DUPLICATE_EMAIL,
      COMMERCIAL_ROW_DUPLICATE_PEER,
      COMMERCIAL_ROW_DUPLICATE_PBX,
      COMMERCIAL_ROW_DUPLICATE_MOBILE,
      COMMERCIAL_ROW_DUPLICATE_SIEBELID,
      SUPERVISOR_ROW_DUPLICATE,
      SUPERVISOR_ROW_DUPLICATE_EMAIL,
      EXTERNAL_SERVICE_ERROR,
      PEER_ALREADY_EXIST_IN_PBX,
      CANNOT_CONNECT_TO_PBX
   }
}
