//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inConcert.iMS.BusinessLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("inConcert.iMS.BusinessLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BestBank_AppLogin {
            get {
                object obj = ResourceManager.GetObject("BestBank_AppLogin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BestBank_EmailHeader {
            get {
                object obj = ResourceManager.GetObject("BestBank_EmailHeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;style&gt;
        ///    @media only screen {
        ///      html {
        ///        min-height: 100%;
        ///        background: #f3f3f3
        ///      }
        ///    }
        ///
        ///    @media only screen and (max-width:596px) {
        ///      .small-float-center {
        ///        margin: 0 auto !important;
        ///        float: none !important;
        ///        text-align: center !important
        ///      }
        ///
        ///      .small-text-center {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BestBank_EmailTemplate_CommercialNew {
            get {
                return ResourceManager.GetString("BestBank_EmailTemplate_CommercialNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;style&gt;
        ///    @media only screen {
        ///      html {
        ///        min-height: 100%;
        ///        background: #f3f3f3
        ///      }
        ///    }
        ///
        ///    @media only screen and (max-width:596px) {
        ///      .small-float-center {
        ///        margin: 0 auto !important;
        ///        float: none !important;
        ///        text-align: center !important
        ///      }
        ///
        ///      .small-text-center {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BestBank_EmailTemplate_CommercialNewPassword {
            get {
                return ResourceManager.GetString("BestBank_EmailTemplate_CommercialNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;style&gt;
        ///    @media only screen {
        ///      html {
        ///        min-height: 100%;
        ///        background: #f3f3f3
        ///      }
        ///    }
        ///
        ///    @media only screen and (max-width:596px) {
        ///      .small-float-center {
        ///        margin: 0 auto !important;
        ///        float: none !important;
        ///        text-align: center !important
        ///      }
        ///
        ///      .small-text-center {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BestBank_EmailTemplate_SupervisorState {
            get {
                return ResourceManager.GetString("BestBank_EmailTemplate_SupervisorState", resourceCulture);
            }
        }
    }
}
